routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//VISITOR PAGES
Route::get('/', 'PagesController@welcome')->name('welcome');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/transparency', 'PagesController@transparency')->name('transparency');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/contact', 'PagesController@contact')->name('contact');

// Auth::routes();
// Authentication Routes...
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');

//DASHBOARDS
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::prefix('/settings')->name('settings.')->middleware('admin')->group(function(){
	Route::get('/','SystemSettingsController@index')->name('index');
	Route::get('/view/{id}','SystemSettingsController@show')->name('view');
	Route::post('/store','SystemSettingsController@store')->name('store');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'SystemSettingsController@update'
	]);
});

//JSON APIs
Route::prefix('/ajax')->name('ajax.')->group(function(){
	Route::prefix('/auth')->name('auth.')->middleware('admin')->group(function(){
		Route::prefix('/settings')->name('settings.')->group(function(){
			Route::get('/{filter}','SystemSettingsController@list');
		});
	});

	Route::prefix('/auth')->name('auth.')->middleware('kagawad')->group(function(){
		Route::prefix('/residents')->name('residents.')->group(function(){
			Route::get('/{filter}','ResidentsController@list');
		});

		Route::prefix('/residences')->name('residences.')->group(function(){
			Route::get('/{filter}','ResidencesController@list');
		});

		Route::prefix('/blotters')->name('blotters.')->group(function(){
			Route::get('/{filter}','BlottersController@list');
		});

		Route::prefix('/users')->name('users.')->group(function(){
			Route::get('/{filter}','UsersController@list');
		});
	});

	Route::prefix('/address')->name('address.')->group(function(){
		Route::get('/provinces', 'AddressesController@get_provinces')->name('provinces');
		Route::post('/citymuns', 'AddressesController@get_citymuns')->name('citymuns');
		Route::post('/brgys', 'AddressesController@get_brgys')->name('brgys');
	});

	Route::prefix('/announcements')->name('announcements.')->group(function(){
		Route::get('/{filter}','AnnouncementsController@list');
	});
});

//RESIDENTS
Route::prefix('/residents')->name('residents.')->middleware('chairman')->group(function(){
	Route::get('/','ResidentsController@index')->name('index');
	Route::post('/store','ResidentsController@store')->name('store');
	Route::get('/view/{resident}','ResidentsController@show')->name('show');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'ResidentsController@update'
	]);
});

//RESIDENCES
Route::prefix('/residences')->name('residences.')->middleware('chairman')->group(function(){
	Route::get('/','ResidencesController@index')->name('index');
	Route::post('/store','ResidencesController@store')->name('store');
	Route::get('/view/{residence}', 'ResidencesController@show')->name('show');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'ResidencesController@update'
	]);
});

//ANNOUNCEMENTS
Route::prefix('/announcements')->name('announcements.')->group(function(){
	Route::get('/','AnnouncementsController@index')->name('index')->middleware('kagawad');
	Route::post('/store','AnnouncementsController@store')->name('store')->middleware('kagawad');
	Route::get('/view/{announcement}','AnnouncementsController@show')->name('show')->middleware('kagawad');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'AnnouncementsController@update'
	])->middleware('chairman');
});

//BLOTTERS
Route::prefix('/blotters')->name('blotters.')->middleware('kagawad')->group(function(){
	Route::get('/','BlottersController@index')->name('index');
	Route::post('/store','BlottersController@store')->name('store');
	Route::get('/view/{blotter}','BlottersController@show')->name('show');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'BlottersController@update'
	]);
});

//USERS
Route::prefix('/users')->name('users.')->middleware('admin')->group(function(){
	Route::get('/','UsersController@index')->name('index');
	Route::post('/store','UsersController@store')->name('store');
	Route::get('/view/{user}','UsersController@show')->name('show');
	Route::put('/update/{user}', [
		'as'	=>	'update',
		'uses' 	=> 	'UsersController@update'
	]);
});

//DATABASE
Route::prefix('/manage/database')->name('database.')->middleware('admin')->group(function(){
	Route::get('/','DatabaseController@index')->name('index');
	Route::post('/backup','DatabaseController@backup')->name('backup');
	Route::post('/restore','DatabaseController@restore')->name('restore');
});

//GENERATE REPORTS
Route::prefix('/reports')->name('reports.')->group(function(){
	Route::get('/','ReportsController@index')->name('index');
	Route::get('/certification/{resident}','ResidentsController@brgy_certification_report')->middleware('kagawad');

	Route::prefix('/summons')->name('summons.')->middleware('kagawad')->group(function(){
		Route::get('/blotter/{blotter}', 'BlottersController@summons_report');
	});
});

//TEST ROUTES
Route::prefix('/development')->name('development.')->middleware('admin')->group(function(){
	Route::prefix('/features')->name('features.')->group(function(){
		Route::get('/qr',function(){
			return QrCode::size(250)->encoding('utf-8')->generate('test', public_path().'/images/residents/qr.png');
		});
	});
});

app/Blotter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blotter extends Model
{
    //
}

app/Http/Controllers/BlottersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use PDF;

use App\Blotter;
use App\InvolvedResident;
use App\Announcement;
use App\Resident;
use App\Residence;

class BlottersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('blotters.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'complainant'   =>  'required',
            'block'         =>  'required|integer',
            'complaint'     =>  'required|string',
        ]);

        $blotter = new Blotter;
        $blotter->complainant = $request["complainant"];
        $blotter->block = $request["block"];
        $blotter->complaint = $request["complaint"];
        $blotter->status = "FOR REVIEW";
        $blotter->save();
        $blotter_id = $blotter->id;

        if ($request["involved_residents"] !== null) {
            foreach ($request["involved_residents"] as $involved_resident) {
                $resident = new InvolvedResident;
                $resident->blotter = $blotter_id;
                $resident->resident = $involved_resident;
                $resident->save();
            }
        }

        if ($request["make_announcement"] === "true") {
            $resident_to_summon = Resident::find($request["complainant"]);
            $announcement = new Announcement;
            $announcement->title = "Blotter #".$blotter->id;
            $announcement->content = "This is to inform that resident ".$resident_to_summon->fname." ".$resident_to_summon->lname." of house number ".$resident_to_summon->house_number." is hereby requested to appear in the barangay office regarding a blotter report filed under #".$blotter->id.".";
            $announcement->priority = "HIGH";
            $announcement->status = "FOR REVIEW";
            $announcement->user = \Auth::user()->username;
            $announcement->save();

            if ($request["involved_residents"] !== null) {
                foreach ($request["involved_residents"] as $involved_resident) {
                    $resident_to_summon = Resident::find($involved_resident);
                    $announcement = new Announcement;
                    $announcement->title = "Blotter #".$blotter->id;
                    $announcement->content = "This is to inform that resident ".$resident_to_summon->fname." ".$resident_to_summon->lname." of house number ".$resident_to_summon->house_number." is hereby requested to appear in the barangay office regarding a blotter report filed under #".$blotter->id.".";
                    $announcement->priority = "HIGH";
                    $announcement->status = "FOR REVIEW";
                    $announcement->user = \Auth::user()->username;
                    $announcement->save();
                }
            }
        }

        return redirect()->route('blotters.index')->with([
            'type'      =>  'positive',
            'title'     =>  'Successful',
            'message'   =>  'Resource save successful',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blotter = Blotter::
                    join('residents','blotters.complainant','=','residents.id')
                    ->where('blotters.id',$id)
                    ->select(
                        'blotters.id',
                        'blotters.block',
                        'blotters.complaint',
                        'blotters.status',
                        'blotters.created_at',
                        'blotters.complainant',
                        'residents.fname',
                        'residents.lname',
                        'residents.house_number',
                        'residents.cp_number',
                        'residents.phone_number'
                    )
                    ->first();

        $involved_residents = InvolvedResident::
                                join('residents','involved_residents.resident','=','residents.id')
                                ->where('involved_residents.blotter',$blotter->id)
                                ->select(
                                    'residents.fname',
                                    'residents.lname',
                                    'residents.house_number',
                                    'residents.cp_number',
                                    'residents.phone_number'
                                )
                                ->get();

        return view('blotters.view')->with([
            'blotter'               =>  $blotter,
            'involved_residents'    =>  $involved_residents,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'block'     =>  'required|integer',
            'complaint' =>  'required|string',
        ]);

        $blotter = Blotter::find($id);
        $blotter->status = $request["status"];
        $blotter->block = "Block ".$request["block"];
        $blotter->complaint = $request["complaint"];
        $blotter->update();

        return redirect()->route('blotters.index')->with([
            'type'      =>  'positive',
            'title'     =>  'Successful',
            'message'   =>  'Resource update successful',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function list($filter)
    {
        if ($filter == "all") {
            $blotters = Blotter::
                        join('residents','blotters.complainant','=','residents.id')
                        ->select(
                            'blotters.id',
                            'residents.fname',
                            'residents.lname',
                            'blotters.created_at',
                            'blotters.status'
                        )->get();
        }
        else if ($filter == "summons") {
            $blotters_complainant = Blotter::
                                    join('residents','blotters.complainant','=','residents.id')
                                    ->select(
                                        'blotters.id',
                                        'residents.fname',
                                        'residents.lname',
                                        'blotters.created_at',
                                        'blotters.status'
                                    );
            $blotters = InvolvedResident::
                        join('blotters','involved_residents.blotter','=','blotters.id')
                        ->join('residents','involved_residents.resident','=','residents.id')
                        ->select(
                            'blotters.id',
                            'residents.fname',
                            'residents.lname',
                            'blotters.created_at',
                            'blotters.status'
                        )
                        ->union($blotters_complainant)
                        ->get();
        }

        return $blotters;
    }

    public function summons_report($blotter_id)
    {
        $blotter = Blotter::find($blotter_id);
        $resident = Resident::find($blotter->complainant);
        $residence = Residence::find($resident->house_number);

        $pdf_blotter = PDF::loadView('reports.blotter',[
            'blotter' => $blotter,
            'resident' => $resident,
            'residence' => $residence,
        ])
        ->setPaper('a4','portrait')
        ->setOptions([
            'defaultFont' => 'Courier'
        ]);
        return $pdf_blotter->stream('Blotter_'.$blotter->id.'_'.date('Y-m-d h:i:s').'.pdf');

        // return view('reports.blotter')->with([
        //     'blotter'   =>  $blotter,
        //     'resident'  =>  $resident,
        // ]);
    }
}

resources/views/blotters/index.blade.php
@extends('layouts.auth')

@section('page-title')
Blotters
@endsection

@section('content')
	<div class = "row">
		<div class = "seven wide column">
			<div class = "ui small equal width text segment">
				<h4 class = "ui header">Add blotter</h4>

				@include('includes.notify')

				<form class = "ui small equal width form" action = "{{ route('blotters.store') }}" method = "POST">
					{{ csrf_field() }}

					<div class = "field">
						<label>Complainant</label>
						<select id = "complainant" name = "complainant" class = "ui small fluid search dropdown" required>

						</select>
					</div>

					<div class = "field">
						<label>Resident/s involved</label>
						<select id = "involved_residents" name = "involved_residents[]" class = "ui small fluid search dropdown" multiple>

						</select>
					</div>

					<div class = "field">
						<label>Block number</label>
						<input type = "number" id = "block" name = "block" min = "1" max = "{{ $brgy_blks }}" required>
					</div>

					<div class = "field">
						<label>Complaint</label>
						<textarea id = "complaint" name = "complaint" rows = "5" required></textarea>
					</div>

					<div class = "field">
						<div class = "ui checkbox">
							<input type = "checkbox" id = "make_announcement" name = "make_announcement" value = "true" checked>
							<label>Create announcment</label>
						</div>
					</div>

					<div class = "field">
						<button type = "submit" class = "ui small primary button">
							<i class = "send icon"></i>
							Submit
						</button>

						<button type = "reset" class = "ui small negative button">
							<i class = "refresh icon"></i>
							Reset fields
						</button>
					</div>
				</form>
			</div>
		</div>

		<div class = "column">
			<div class = "ui small equal width text segment">
				<h4 class = "ui header">List of blotters</h4>

				<table id = "tblListOfBlotters" class = "ui small celled striped table" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>ID</th>
							<th>Complainant</th>
							<th>Date filed</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
@endsection

resources/views/blotters/view.blade.php
@extends('layouts.auth')

@section('page-title')
View blotter #{{ $blotter->id }}
@endsection

@section('content')
	<div class = "row">
		<div class = "seven wide column">
			<div class = "ui small equal width text segment">
				<h4 class = "ui header">Edit blotter report #{{ $blotter->id }}</h4>

				<form class = "ui small equal width form" action = "{{ route('blotters.update', $blotter->id) }}" method = "POST">
					{{ csrf_field() }}
					{{ method_field('PUT') }}

					@include('includes.notify')

					<div class = "field">
						<label>Status</label>
						@if(auth()->user()->level == "admin" || auth()->user()->level == "captain" || auth()->user()->level == "kagawad")
							<select id = "status" name = "status" class = "ui small fluid search dropdown">
								<option value = "FOR REVIEW">FOR REVIEW</option>
								<option value = "REVIEWED">REVIEWED</option>
								<option value = "RESOLVED">RESOLVED</option>
							</select>
						@else
							<select id = "status" name = "status" class = "ui small fluid search dropdown" readonly>
								<option value = "FOR REVIEW">FOR REVIEW</option>
								<option value = "REVIEWED">REVIEWED</option>
								<option value = "RESOLVED">RESOLVED</option>
							</select>
						@endif
					</div>

					<div class = "field">
						<label>Complainant</label>
						<input type = "text" value = "{{ $blotter->fname }} {{ $blotter->lname }} (House #{{ $blotter->house_number }})" readonly>
					</div>

					<div class = "field">
						<label>Block number</label>
						<input type = "number" id = "block" name = "block" min = "1" max = "{{ $brgy_blks }}" value = "{{ $blotter->block }}" required>
					</div>

					<div class = "field">
						<label>Complaint</label>
						<textarea id = "complaint" name = "complaint" rows = "5" required>{{ $blotter->complaint }}</textarea>
					</div>

					<div class = "field">
						<a href = "{{ route('blotters.index') }}" class = "ui small button">
							<i class = "left arrow icon"></i>
							Back
						</a>

						<button type = "submit" class = "ui small button">
							<i class = "send icon"></i>
							Submit
						</button>

						<button type = "reset" class = "ui small button">
							<i class = "refresh icon"></i>
							Reset fields
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
	<script type = "text/javascript">
		$(document).ready(function(){
			$('#status').dropdown('set selected','{{ $blotter->status }}');
		});
	</script>
@endsection