routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//VISITOR PAGES
Route::get('/', 'PagesController@welcome')->name('welcome');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/transparency', 'PagesController@transparency')->name('transparency');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/contact', 'PagesController@contact')->name('contact');

// Auth::routes();
// Authentication Routes...
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');

//DASHBOARDS
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::prefix('/settings')->name('settings.')->middleware('admin')->group(function(){
	Route::get('/','SystemSettingsController@index')->name('index');
	Route::get('/view/{id}','SystemSettingsController@show')->name('view');
	Route::post('/store','SystemSettingsController@store')->name('store');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'SystemSettingsController@update'
	]);
});

//JSON APIs
Route::prefix('/ajax')->name('ajax.')->group(function(){
	Route::prefix('/auth')->name('auth.')->middleware('admin')->group(function(){
		Route::prefix('/settings')->name('settings.')->group(function(){
			Route::get('/{filter}','SystemSettingsController@list');
		});
	});

	Route::prefix('/auth')->name('auth.')->middleware('kagawad')->group(function(){
		Route::prefix('/residents')->name('residents.')->group(function(){
			Route::get('/{filter}','ResidentsController@list');
		});

		Route::prefix('/residences')->name('residences.')->group(function(){
			Route::get('/{filter}','ResidencesController@list');
		});

		Route::prefix('/blotters')->name('blotters.')->group(function(){
			Route::get('/{filter}','BlottersController@list');
		});

		Route::prefix('/users')->name('users.')->group(function(){
			Route::get('/{filter}','UsersController@list');
		});
	});

	Route::prefix('/address')->name('address.')->group(function(){
		Route::get('/provinces', 'AddressesController@get_provinces')->name('provinces');
		Route::post('/citymuns', 'AddressesController@get_citymuns')->name('citymuns');
		Route::post('/brgys', 'AddressesController@get_brgys')->name('brgys');
	});

	Route::prefix('/announcements')->name('announcements.')->group(function(){
		Route::get('/{filter}','AnnouncementsController@list');
	});
});

//RESIDENTS
Route::prefix('/residents')->name('residents.')->middleware('chairman')->group(function(){
	Route::get('/','ResidentsController@index')->name('index');
	Route::post('/store','ResidentsController@store')->name('store');
	Route::get('/view/{resident}','ResidentsController@show')->name('show');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'ResidentsController@update'
	]);
});

//RESIDENCES
Route::prefix('/residences')->name('residences.')->middleware('chairman')->group(function(){
	Route::get('/','ResidencesController@index')->name('index');
	Route::post('/store','ResidencesController@store')->name('store');
	Route::get('/view/{residence}', 'ResidencesController@show')->name('show');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'ResidencesController@update'
	]);
});

//ANNOUNCEMENTS
Route::prefix('/announcements')->name('announcements.')->group(function(){
	Route::get('/','AnnouncementsController@index')->name('index')->middleware('kagawad');
	Route::post('/store','AnnouncementsController@store')->name('store')->middleware('kagawad');
	Route::get('/view/{announcement}','AnnouncementsController@show')->name('show')->middleware('kagawad');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'AnnouncementsController@update'
	])->middleware('chairman');
});

//BLOTTERS
Route::prefix('/blotters')->name('blotters.')->middleware('kagawad')->group(function(){
	Route::get('/','BlottersController@index')->name('index');
	Route::post('/store','BlottersController@store')->name('store');
	Route::get('/view/{blotter}','BlottersController@show')->name('show');
	Route::put('/update/{id}', [
		'as'	=>	'update',
		'uses' 	=> 	'BlottersController@update'
	]);
});

//USERS
Route::prefix('/users')->name('users.')->middleware('admin')->group(function(){
	Route::get('/','UsersController@index')->name('index');
	Route::post('/store','UsersController@store')->name('store');
	Route::get('/view/{user}','UsersController@show')->name('show');
	Route::put('/update/{user}', [
		'as'	=>	'update',
		'uses' 	=> 	'UsersController@update'
	]);
});

//DATABASE
Route::prefix('/manage/database')->name('database.')->middleware('admin')->group(function(){
	Route::get('/','DatabaseController@index')->name('index');
	Route::post('/backup','DatabaseController@backup')->name('backup');
	Route::post('/restore','DatabaseController@restore')->name('restore');
});

//GENERATE REPORTS
Route::prefix('/reports')->name('reports.')->group(function(){
	Route::get('/','ReportsController@index')->name('index');
	Route::get('/certification/{resident}','ResidentsController@brgy_certification_report')->middleware('kagawad');

	Route::prefix('/summons')->name('summons.')->middleware('kagawad')->group(function(){
		Route::get('/blotter/{blotter}', 'BlottersController@summons_report');
	});
});

//TEST ROUTES
Route::prefix('/development')->name('development.')->middleware('admin')->group(function(){
	Route::prefix('/features')->name('features.')->group(function(){
		Route::get('/qr',function(){
			return QrCode::size(250)->encoding('utf-8')->generate('test', public_path().'/images/residents/qr.png');
		});
	});
});

resources/views/includes/auth-navbar.blade.php
<div class = "ui large top fixed borderless stackable menu" style="padding-left: 15rem;">
    <a href = "{{ route('welcome') }}" class = "header item">
        <i class = "large laravel icon"></i>
        {{ config('app.name') }}
    </a>

    <div class = "right item">
    	Welcome, {{ auth()->user()->fname }} {{ auth()->user()->lname }}! You're logged in as {{ assert_a_an( ucwords(auth()->user()->level) ) }} {{ (auth()->user()->level) }}
    </div>
</div>

resources/views/includes/auth-sidebar.blade.php
<div class = "ui visible inverted borderless vertical sidebar menu" style = "z-index: 1000;">
    <a href = "{{ route('dashboard') }}" class = "item">
        <i class = "chart bar icon"></i>
        Dashboard
    </a>

    <a href = "{{ route('announcements.index') }}" class = "item">
        <i class = "bullhorn icon"></i>
        Announcements
    </a>

    <a href = "{{ route('blotters.index') }}" class = "item">
        <i class = "quote left icon"></i>
        Blotters
    </a>

    @if(auth()->user()->level == "admin")
        <a href = "{{ route('database.index') }}" class = "item">
            <i class = "database icon"></i>
            Database Manager
        </a>
    @endif
    
    <a href = "{{ route('reports.index') }}" class = "item">
        <i class = "print icon"></i>
        Forms and Reports
    </a>

    @if(auth()->user()->level == "chairman" || auth()->user()->level == "admin")
        <a href = "{{ route('residences.index') }}" class = "item">
            <i class = "home icon"></i>
            Residences Registry
        </a>
        <a href = "{{ route('residents.index') }}" class = "item">
            <i class = "id card icon"></i>
            Residents Registry
        </a>
    @endif

    @if(auth()->user()->level == "admin")
        <a href = "{{ route('settings.index') }}" class = "item">
            <i class = "cog icon"></i>
            System Settings
        </a>

        <a href = "{{ route('users.index') }}" class = "item">
            <i class = "user icon"></i>
            User Manager
        </a>
    @endif
    
    <a href = "{{ route('logout') }}" class = "item">
        <i class = "sign-out icon"></i>
        Log out
    </a>
</div>'

resources/views/includes/notify.blade.php
@if($errors->any())
	<div class = "ui fluid negative message">
		<i class = "close icon"></i>
		<div class = "header">{{ count($errors->all()) }} {{ count($errors->all) > 1 ? "validations" : "validation" }} failed</div>
		<ul class = "list">
			@foreach($errors->all() as $error)
				<li class = "item">{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

@if(session()->has('type'))
	<div class = "ui {{ session('type') }} message">
		<i class = "close icon"></i>
		<div class = "header">{{ session('title') }}</div>
		<p>
			{{ session('message') }}
		</p>
	</div>
@endif

resources/views/includes/side-content.blade.php
<div class = "four wide column">
    <div class = "ui grid">
        <div class = "row">
            <div class = "column">
                <div class = "ui small segment">
                    <h4 class = "ui header">Announcements</h4>

                    @if(count($all_announcements) > 0)
                        <div class = "ui relaxed bulleted list">
                            @foreach($all_announcements as $all_announcement)
                                <div class = "item">{{ $all_announcement->content }} (Posted by: {{ $all_announcement->fname }} {{ $all_announcement->lname }})</div>
                            @endforeach
                        </div>
                    @else
                        <p>No advisories found</p>
                    @endif
                </div>
            </div>
        </div>

        {{-- <div class = "row">
            <div class = "column">
                <div class = "ui small segment">
                    <h4 class = "ui header">Public Advisories</h4>

                    @if(count($high_priority_announcements) > 0)
                        <div class = "ui relaxed ordered list">
                            @foreach($high_priority_announcements as $high_priority_announcement)
                                <div class = "item">{{ $high_priority_announcement->content }} (Posted by: {{ $high_priority_announcement->fname }} {{ $high_priority_announcement->lname }})</div>
                            @endforeach
                        </div>
                    @else
                        <p>No advisories found</p>
                    @endif
                </div>
            </div>
        </div> --}}

        <div class = "row">
            <div class = "column">
                <div class = "ui small segment">
                    <h4 class = "ui header">Administrator Login</h4>
                    @if(Auth::check())
                        You are logged in, {{ auth()->user()->level }} {{ auth()->user()->fname }}.
                        <a href = "{{ route('dashboard') }}">
                            Go to Dashboard
                        </a>
                    @else
                        <a href = "{{ route('login') }}" class = "ui fluid primary button">
                            Click to login
                        </a>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/includes/un-auth-navbar.blade.php
<div class = "ui large top fixed stackable borderless menu">
    <a class = "header item" href = "#">
        <i class = "large laravel icon"></i>
        {{-- <span id = "lblBrgyName"></span> --}}
        {{ $brgy_name ?? 'Name has not been set yet' }}
    </a>

    <div class = "right menu">
        <a class = "item" href = "{{ route('welcome') }}">Home</a>
        <a class = "item" href = "{{ route('about') }}">About us</a>
        <a class = "item" href = "{{ route('transparency') }}">Transparency</a>
        <a class = "item" href = "{{ route('services') }}">Services</a>
        <a class = "item" href = "{{ route('contact') }}">Contact us</a>
    </div>
</div>